name: CalculatorUI
version: 1.0.0-beta
main: NaufalBlazeYT\CalculatorUI\Main
api: 3.0.0
author: NaufalBlazeYT
commands:
  calculatorui:
   description: "CalculatorUI command"
   usage: /calc
   aliases:
     - calc
     - calcui
   permission: calculatorui.command
   permission-message: "§cYou do not have permission"
permissions:
  calculatorui.command:
    default: op
    description: "Allow user to use CalculatorUI command"