name: CalculatorUI
main: NaufalBlazeYT\CalculatorUI\Main
api: 3.0.0
version: 1.0.0-beta
author: NaufalBlazeYT

commands:
  cal:
   description: "CalculatorUI Commands"
   permission: calculatorui.command
   usage: /cal

permissions:
  calculatorui.command:
    default: op
    description: "CalculatorUI Commands"
